### PR TITLE
Assignment1

### PR DESCRIPTION
**Pull request by jdriscoll1**
Did not have a partner.
Got code to run and compile and all tests have passed locally.

### CODE REVIEW

**Comment by jacobnewcomb** [comment]
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔

Great job it seems like everything is running good! I appreciate how concise your changes were.

**Comment by mhtran23** [comment]
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔
My only real critique is you add return spaces where it was kind of unnecessary which add more code lines making the code look longer, other than that, your changes looks good

**Comment by TriciaFaust** [comment]
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔

**Review by TriciaFaust — APPROVED** [review]
Looks good.  All problems addressed.

**Comment by mmwoodfo** [comment]
Good job - you had alot of whitespace changes that were cluttering your change log, looks like @mhtran23 left a good comment about that.

**Pull request closed without merging**
