### PR TITLE
Assignment 1

### PR DESCRIPTION
**Pull request by StrangeRanger**
@hallen10 (Hunter Allen)

### CODE REVIEW

**Review by EvanBartels — COMMENTED** [review]
Pull Request title includes "Assignment 1" in the title ❌
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ❌

Change PR name to include Assignment 1 in the title somewhere
Although not completely sure, I don't think moving where the *100 is changes the outcome of the test, consider how the function works and what's passed in
Consider doing the Extra Credit, there are definitely things that could be added to the program

**Comment by JessicaH46** [comment]
Pull Request title includes "Assignment 1" in the title ❌
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ✔
Issue 2: Unit test properly passes ✔❌

Just a reminder that you need to change your pull request name to include the Assignment 1 in it, you did target the correct branch and the application crash looks to be resolved. Good work there! For issue 2, I'm not sure if that was the correct way to do it as when I did it the problem seemed to be the type and I had to cast them as doubles. Other then that good job!

**Comment by StrangeRanger** [comment]
> Pull Request title includes "Assignment 1" in the title ❌
> 
> Pull Request targets Assignment 1 branch ✔
> 
> Issue 1: Application no longer crashes ✔
> 
> Issue 2: Unit test properly passes ❌
> 
> 
> 
> Change PR name to include Assignment 1 in the title somewhere
> 
> Although not completely sure, I don't think moving where the *100 is changes the outcome of the test, consider how the function works and what's passed in
> 
> Consider doing the Extra Credit, there are definitely things that could be added to the program

That's strange. It passed all tests for me and moving the *100 worked.

**Comment by StrangeRanger** [comment]
> Pull Request title includes "Assignment 1" in the title ❌
> 
> Pull Request targets Assignment 1 branch ✔
> 
> Issue 1: Application no longer crashes ✔
> 
> Issue 2: Unit test properly passes ✔❌
> 
> 
> 
> Just a reminder that you need to change your pull request name to include the Assignment 1 in it, you did target the correct branch and the application crash looks to be resolved. Good work there! For issue 2, I'm not sure if that was the correct way to do it as when I did it the problem seemed to be the type and I had to cast them as doubles. Other then that good job!
> 
Are you saying that it passed the unit tests or no?

**Comment by EvanBartels** [comment]
With the new changes from your recent commit I would say it looks good @StrangeRanger, the only thing that could be a problem is I believe the percentages that way have a lot of decimals so it doesn't look clean, but not sure how much of a problem that is. You could either use a method to limit decimals shown or cast it back to an int after the calculation. Looks good otherwise!

**Comment by JessicaH46** [comment]
> @JessicaH46 Did the unit testing pass for you, or no?

Yes it passed! Looks good and it has the correct name so I think you are all set! Good work on this assignment!
@StrangeRanger

**Comment by StrangeRanger** [comment]
@EvanBartels @JessicaH46 Awesome, thank you both.

**Comment by JLee35** [comment]
Looks good, and good job responding to peer reviews.

**Pull request closed without merging**
