### PR TITLE
Assignment4 - Ian Kaiserman

### PR DESCRIPTION
**Pull request by Afterlyte**
paired with @eroadhouse

EC attempted for items/properties in a single file (this was in the original submission but I forgot to note it)

### CODE REVIEW

**Comment by StrangeRanger** [comment]
Will Review

**Comment by Malcolm-Shepherd** [comment]
## Tasks

- Define a full name record (first, last, middle) handling optional and null appropriately. ✔
  - Provide a comment on the full name record on why you selected to define a value or a reference type and ✔
  - Provide a comment on the full name record on why or why not the type is immutable. ✔
- Define an `IEntity` interface: ✔
  - Add an Id property of type `Guid` that is an init-only setter. ✔
  - Add a Name property that is `string`. ✔
- Define an abstract base class that implements `IEntity` - appropriately choosing to implement the interface explicitly or implicitly. ✔
  - Do not implement the `Name` property in this abstract class. ✔
  - Do force any derived classes to provide an implementation for `Name`. ✔
- Define book, student, and employee records - all with entity capabilities. ✔
  - Choose a thoughtful approach for the value of `Name` for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ✔
  - Provide a comment on each interface **member** in each entity explaining why you implemented it implicitly or explicitly. ❌
  - You should consider the relationship between Student and Employee and refactor the common code shared between them. ❌
  - Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
  - Test that the equality behavior on these entities behaves as expected. ✔
  - Provide a comment on each interface method explaining why you implemented it implicitly or explicitly.
- Unit test the Storage class using various entities to ensure that there are no bugs. ✔
- Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.)✔
  - Pay special attention to the CreateLogger methods throughout.

**Comment by Malcolm-Shepherd** [comment]
## Provide a comment on each interface member in each entity explaining why you implemented it implicitly or explicitly. 
No comment on book's implementation of name. I also don't agree with your implementation of name. If I called Book.Name, I would expect the title and not the author's name.
## You should consider the relationship between Student and Employee and refactor the common code shared between them. 
Code wasn't refactored. You copied the shared code into a new interface then didn't use the interface or remove the shared code in the original classes.

**Review by StrangeRanger — COMMENTED** [review]
## Tasks

- Define a full name record (first, last, middle) handling optional and null appropriately. ✔
  - Provide a comment on the full name record on why you selected to define a value or a reference type and ✔
  - Provide a comment on the full name record on why or why not the type is immutable. ✔
- Define an `IEntity` interface: ✔
  - Add an Id property of type `Guid` that is an init-only setter. ✔
  - Add a Name property that is `string`. ✔
- Define an abstract base class that implements `IEntity` - appropriately choosing to implement the interface explicitly or implicitly. ✔
  - Do not implement the `Name` property in this abstract class. ✔
  - Do force any derived classes to provide an implementation for `Name`. ✔
- Define book, student, and employee records - all with entity capabilities. ✔
  - Choose a thoughtful approach for the value of `Name` for each type of entity. In all cases, there should be no backing field for Name (not even one generated by an automatically implemented property) - consider a calculated property. ✔
  - Provide a comment on each interface **member** in each entity explaining why you implemented it implicitly or explicitly. ❌
    - **DOESN'T SEEM LIKE YOU PROVIDED ANY COMMENTS ON THE INTERFACE MEMBER THEMSELVES**
  - You should consider the relationship between Student and Employee and refactor the common code shared between them. ❌
    - **WAS REFACTORED BUT IT DOESN'T SEEM LIKE IT WAS EVER IMPLIMENTED INTO EITHER  STUDENT OR EMPLOYEE**
  - Given the properties on the full name record, you should consider which entities it makes sense to use it. ✔
  - Test that the equality behavior on these entities behaves as expected. ✔
  - Provide a comment on each interface method explaining why you implemented it implicitly or explicitly.
- Unit test the Storage class using various entities to ensure that there are no bugs.
- Code review (using TODO: comments if there are any issues - which there may not be) all logger-related classes.)
  - Pay special attention to the CreateLogger methods throughout.

## Fundamentals

- Be sure you enable:
  - Enable Nullability for all projects  ✔
  - Set `LangVersion` and the `TargetFramework` to the latest released versions available (preview versions optional) ✔
  - Ensure that you turn on code analysis for all projects(EnableNETAnalyzers) ✔
- **Ensure there are no errors or warnings (including code analysis warnings)** ✔
- **All of the above should be unit tested** ✔
- **Choose simplicity over complexity** ✔

## Extra Credit

- Refactor your project files to put common properties and/or items into a single file. ❌
- Convert `ILogger.CreateLogger` to a generic method. ❌
  - Returns the logger classes type that is to be created. ❌
  - Has a type parameter for the configuration type ❌

## Other Notes

You did a pretty good job. After looking at your code, it made me realize that I made some stuff more complicated than it needed to be. There honestly isn't a whole lot that I can say on what you could do better, other than the comments I made above, so I do apologize for this lack luster feedback.

**Review by mmwoodfo — COMMENTED** [review]
Good job!

**Pull request closed without merging**
